parameters:
#    leicester_civic_bus_hack_mistabus_api.example.class: LeicesterCivicBusHack\MistabusAPIBundle\Example

services:
#    leicester_civic_bus_hack_mistabus_api.example:
#        class: %leicester_civic_bus_hack_mistabus_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    mistabus_delay:
        class: LeicesterCivicBusHack\MistabusAPIBundle\Services\DelayService
        arguments: [@doctrine.orm.default_entity_manager]

    mistabus_lookup:
        class: LeicesterCivicBusHack\MistabusAPIBundle\Services\LookupService
        arguments: [@doctrine.orm.default_entity_manager]

